common:
  containerRegistryURL: "sidharthacr.azurecr.io"
  ingressClassName: nginx


backend:
  replicas: 2
  image:
    name: todoapp
    tag: 103
  port: 80
 # connectionString: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:sidharthsqlserver.database.windows.net,1433;Database=sidharthsqldatabase;Uid=sidharthsqlserver;Pwd=Sidr@j123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ServicePort: 80
  targetPort: 80


