apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apps
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.common.containerRegistryURL }}/{{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: CONNECTION_STRING
              value: "{{ .Values.backend.connectionString }}"
