apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}     # should be nginx, not backend
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-apps
            port:
              number: {{ .Values.backend.ServicePort }}